---
title: "Topic ideas"
author: "Team World"
date: "10/11/19"
output: github_document
---

## Topic Ideas

### Idea #1

Data related to Climate Change. Specifically, we might want to take a look at the contributing factors to our current climate crisis or look at how various indicators of climate have changed in the last 50 years. Alternatively, we might be able to use regression (whick we will soon learn) to predict the state of the climate considering trends continue as is.

### Idea #2

We wanted to look at Airbnb data because we thought this could be interesting insight into the economic housing market in NYC. We could compare price by neighborhood and borough which could provide interesting insights into the cost of living in NYC.

### Idea #3 

<<<<<<< HEAD
We are interested in Uber data because we want to are curious how certain factors such as time, location, and distance, will play a role in the price of Uber rides. We are also interested in eventually using regression and statistics to predict the prices of Uber rides based on location, time, and distance.
=======
We are interested in Uber and Lyft data because we want to are curious how certain factors such as time, location, and distance, will play a role in the price of Uber/Lyft rides. We are also interested in eventually using regression and statistics to predict the prices of Uber rides based on location, time, and distance.
>>>>>>> 060e63541038088e17f581d705e1d7fdbd2a7ab7

### Idea #4

We are interested in the Youtube data because it provides us with staightforward numerical and categorical data. We are curious about how the time or country of publication can impact the popularity of the posted video in terms of likes and comments. We could also look at the types of videos that tend to disable their comments or ratings through the description as well as do text analysis on the tags. We can also add additional datasets through inner-join to increase the variables we can analyze.

## Datasets

### Dataset #1
https://www.kaggle.com/theworldbank/world-bank-climate-change-data

### Dataset #2
https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data

### Dataset #3
https://www.kaggle.com/fivethirtyeight/uber-pickups-in-new-york-city?fbclid=IwAR1CCcEglvGDHGGltaTRPeXzH4sF0uzriZRo8pzkVMxpxBj6oexXl7YN8W0

### Dataset #4
https://www.kaggle.com/datasnaek/youtube-new
